# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b25923128dbd71f37152f9147c9457b150b830d74eb4e062ab19ea97538049941dcf88cac04501f76524f9d66a0154e145e0715cfc407a0b928c955f6291fe9

test:
  secret_key_base: 7dcd0781081a1e18a79ab8194a6914a4f6c16a9c990681702ec95c4ee6cba202c61c54932f146f301d2ae04f999e80baf41cd2f8416f9114e4103c82d64707e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
